name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [17]
    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: mvn compile

  test:
    runs-on: self-hosted
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [17]
    needs: build
    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: mvn test

  package:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Package
        run: mvn package
